name: "[App] Deploy to staging"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install & build
        run: |
          # https://github.com/yarnpkg/yarn/issues/2629
          while ! yarn install; do echo --- ; done
          yarn workspace request-shared build
          yarn workspace request-ui build
          yarn workspace app build
        env:
          CI: false
          PUBLIC_URL: https://baguette-v2.request.
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-build-artifact
          path: packages/app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    #if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: app-build-artifact
          path: packages/app/build
      - uses: benjlevesque/s3-sync-action@master
        env:
          CI: false
          SOURCE_DIR: "packages/app/build"
          AWS_REGION: eu-west-1
          AWS_S3_BUCKET: baguette-v2.request.network
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
